config/routes.rb
Rails.application.routes.draw do
  resources :qr_codes

  root 'welcome#index'
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'
  get 'profile', to: 'users#profile'
  patch 'users/update_profile_pic', to: 'users#update_profile_pic', as: 'update_profile_pic'
 



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    # makes Current.user accessible in view files.
    attribute :user
  end

app/models/qr_code.rb
require 'rqrcode'
require 'rqrcode_svg'
class QrCode < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  def qrcode_svg(qr_code_data, size: 4)
    qr = RQRCode::QRCode.new(qr_code_data)
    svg = qr.as_svg(
      color: "000",
      shape_rendering: "crispEdges",
      module_size: size,
      standalone: true,
      use_path: true
    )

    return svg.html_safe
  end
  # Add this line to include the product_name attribute
  attribute :product_name, :string
end

app/models/user.rb
class User < ApplicationRecord
     has_many :qr_codes
  
     has_one_attached :profile_pic
     # adds virtual attributes for authentication
     has_secure_password
     # validates email and username
     validates :username, presence: true, uniqueness: true, format: { with: /\A[a-zA-Z0-9._-]{3,16}\z/, message: 'Invalid username' }
     validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    def set_current_user
      # finds user with session data and stores it if present
      Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
    end
    def require_user_logged_in!
      # allows only logged in user
      redirect_to sign_in_path, alert: 'You must be signed in' if Current.user.nil?
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    # allows only logged in users
    before_action :require_user_logged_in!
    def edit; end
    def update
      # update user password
      if Current.user.update(password_params)
        redirect_to root_path, notice: 'Password Updated'
      else
        render :edit
      end
    end
    private
    def password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
  end

app/controllers/qr_codes_controller.rb
class QrCodesController < ApplicationController
  before_action :set_qr_code, only: %i[ show edit update destroy ]
  require 'chunky_png'

  # GET /qr_codes or /qr_codes.json
  def index
    @qr_codes = QrCode.all
  end

  # GET /qr_codes/1 or /qr_codes/1.json
  def show
    @qr_code = QrCode.find(params[:id])
    @remove_navbar=true
  end

  # GET /qr_codes/new
  def new
    @user = User.find(session[:user_id])
    @qr_code = QrCode.new
  end

  # GET /qr_codes/1/edit
  def edit
  end
  
  # POST /qr_codes or /qr_codes.json
  def create
    @qr_code = QrCode.new(qr_code_params)
    @qr_code.user_id = session[:user_id]

    if @qr_code.save
      qr = RQRCode::QRCode.new(qr_code_url(@qr_code.id))
      png = qr.as_png(
        bit_depth: 1,
        border_modules: 4,
        color_mode: ChunkyPNG::COLOR_GRAYSCALE,
        color: "black",
        file: nil,
        fill: "white",
        module_px_size: 6,
        resize_exactly_to: false,
        resize_gte_to: false,
        size: 200
      )
      @qr_code.image.attach(
        io: StringIO.new(png.to_s),
        filename: "#{@qr_code.id}.png",
        content_type: "image/png"
      )      
      redirect_to profile_path, notice: "QR code was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
    
  end

  # PATCH/PUT /qr_codes/1 or /qr_codes/1.json
  def update
    respond_to do |format|
      if @qr_code.update(qr_code_params)
        format.html { redirect_to qr_code_url(@qr_code), notice: "Qr code was successfully updated." }
        format.json { render :show, status: :ok, location: @qr_code }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @qr_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qr_codes/1 or /qr_codes/1.json
  def destroy
    @qr_code.destroy

    respond_to do |format|
      format.html { redirect_to qr_codes_url, notice: "Qr code was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qr_code
      @qr_code = QrCode.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def qr_code_params
      params.require(:qr_code).permit(:product_name, :expiration_code, :image)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    # instantiates new user
    def new
      @user = User.new
    end
    def create
      @user = User.new(user_params)
      if @user.save
      # stores saved user id in a session
        session[:user_id] = @user.id
        redirect_to root_path, notice: 'Successfully created account'
      else
        render :new
      end
    end
    private
    def user_params
      # strong parameters
      params.require(:user).permit( :username, :password, :password_confirmation, :email, :profile_pic, :company)
    end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new; end
    def create
      user = User.find_by(username: params[:username])
      # finds existing user, checks to see if user can be authenticated
      if user.present? && user.authenticate(params[:password])
      # sets up user.id sessions
        session[:user_id] = user.id
        redirect_to profile_path, notice: 'Logged in successfully'
      else
        flash.now[:alert] = 'Invalid email or password'
        render :new
      end
    end
    def destroy
      # deletes user session
      session[:user_id] = nil
      redirect_to root_path, notice: 'Logged Out'
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def user_params
        params.require(:user).permit(:profile_pic)
    end
    def profile
        profile_path
    end
    def edit
        @user = User.find(session[:user_id])
    end
    def update_profile_pic
        user_id = session[:user_id]
        @user = User.find(user_id)
        if @user.update(user_params)
        # stores saved user id in a session
          redirect_to profile_path
        else
          render :edit
        end
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def logged_in?
        !!session[:user_id]
    end

    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if !!session[:user_id]
    end
end

app/helpers/qr_codes_helper.rb
module QrCodesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<div class=" flex justify-between">
        <h2 class="text-4xl p-3" style="font-family: 'Rampart One', cursive;">EXPIRATION GENERATOR</h2>
        <div class="p-3">
            <% if Current.user %>
            <p class="text-2xl pr-3"><%= link_to Current.user.company, profile_path %></p>
            <%= link_to 'Edit Password', edit_password_path %>
            <%= button_to 'Logout', logout_path, method: :delete %>
            <% else %>
            <%= link_to 'Sign Up', sign_up_path, class: 'text-2xl' %>
            or
            <%= link_to 'Login', sign_in_path, class: 'text-2xl' %>
            <% end %>
        </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QrGenerator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Rampart+One&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Rampart+One&family=Ultra&display=swap" rel="stylesheet">
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
<script src="https://cdn.tailwindcss.com"></script>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <% if @remove_navbar %>
      <%= yield %>
    <% else %>
      <%= render partial: 'layouts/navbar' %>
      <%= yield %>
    <% end %>

</body>
</html>

app/views/qr_codes/_form.html.erb
<%= form_with model: @qr_code, url: qr_codes_path do |f| %>

    <div class="my-5">
    <%= f.label :product_name %>
    <%= f.text_field :product_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= f.label :expiration_code %>
    <%= f.text_field :expiration_code, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= f.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/qr_codes/_qr_code.html.erb
<div id="<%= dom_id qr_code %>">
  <div class="my-5 flex">

 <strong class=" text-2xl mr-12 self-center font-medium mb-1"><%= User.find(qr_code.user_id).company %></strong>

      <%= image_tag  User.find(qr_code.user_id).profile_pic, class:"rounded-full w-40 h-40 m-auto my-4" %>
  </div>

  <p class="my-5 text-xl">
    <strong class="block font-medium mb-1">Product Name:</strong>
    <%= qr_code.product_name %>
  </p>

  <p class="my-5 text-xl">
    <strong class="block font-medium mb-1 "> Expiration Date:</strong>
    <%= qr_code.expiration_code %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this qr code", qr_code, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this qr code', edit_qr_code_path(qr_code), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/qr_codes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Edit your QR Code</h1>

  <%= render "form", qr_code: @qr_code %>
  <%= button_to 'Destroy this QR Code', qr_code_path(@qr_code), method: :delete, class: "mt-2 text-white rounded-lg py-3 px-5 bg-red-500 font-medium" %>
  <%= link_to "Back to profile", profile_path, class: "rounded-lg py-3 mt-2  inline-block px-5 bg-gray-100  font-medium" %>
</div>

app/views/qr_codes/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Qr codes</h1>
    <%= link_to 'New qr code', new_qr_code_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="qr_codes" class="min-w-full">
    <%= render @qr_codes %>
  </div>
</div>

app/views/qr_codes/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New qr code</h1>

  <%= render "form", qr_code: @qr_code %>

  <%= link_to 'Back to Profile', profile_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/qr_codes/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto ">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @qr_code %>
   
  </div>
</div>

app/views/users/new.html.erb
<h1>New Users </h1>
<%=form_for @user do |f| %>
    <%=f.label :username %>
    <%=f.text_field :username %><br>
    <%=f.label :email %>
    <%=f.text_field :email %><br>
    <%=f.label :company %>
    <%=f.text_field :company %><br>
    <%=f.label :password %>
    <%=f.password_field :password %><br>
    <%=f.submit "Create Account" %>
<% end %>

app/views/users/profile.html.erb
 <div>
    <div class="flex bg-blue-100">
        <div class="basis-1/4"> 
            <h1 class="text-center text-2xl"><%= Current.user.company %> </h1>
              <% if Current.user.profile_pic.attached? %>
                <%= image_tag Current.user.profile_pic, class:"rounded-full w-40 h-40 m-auto my-4" %>
                <% else %>
            <%= form_for Current.user, url: update_profile_pic_path, html: { method: :patch, multipart: true } do |f| %>
            <div class="picture_label">
            <%= f.file_field :profile_pic, class: 'custom-file-input' %>
           <%= f.label :profile_pic, "Upload", class: 'custom-file-label' %>
           </div>
             <%= f.submit "Update Company Logo" , class:"my-4 mx-4 text-white rounded-lg py-3 px-5 inline-block bg-emerald-500 font-medium" %>
             <% end %>
            <% end %>
        </div>  
        <div class="basis-3/4 "> 
    <h3 class=" text-2xl">Generate New QR Codes Here</h3>
    <%= link_to "New QR Code", new_qr_code_path, class: "my-4 mx-4 text-white rounded-lg py-3 px-5 inline-block bg-emerald-500 font-medium" %>    
        </div>        
    </div>
    

    <div class="flex mt-4 grid-rows-5">
<% Current.user.qr_codes.each do |qr_code| %>
  <div class="rounded flex-col profile-qr bg-orange-50 px-5 justify-center	p-3 m-3">
    <h3 class="font-medium text-lg">Product Name: <%= qr_code.product_name %></h3>
    <p class="font-medium text-lg">Expiration Code: <%= qr_code.expiration_code %></p>
 <%= image_tag qr_code.image, class:"mx-auto" %> 
 <div class="flex justify-center">
   <%= link_to 'Edit', edit_qr_code_path(qr_code.id), class: "mt-2 rounded-lg py-2 px-2 bg-blue-400 mx-1" %>
   <%= link_to 'View', qr_code_path(qr_code.id), class: "mt-2 rounded-lg py-2 px-2 bg-blue-400 mx-1" %>
   <%= link_to "Download", qr_code.image, download: "qr_code.png", class: "mt-2 rounded-lg py-2 px-2 bg-blue-400 mx-1" %>
</div>
</div>
<% end %>
</div>
 </div>

app/views/welcome/index.html.erb
<div>
    
    <div class="bg-blue-100">
        <div class="flex-col ">
        <div class="md:flex  justify-center">
        
            <img class="p-8 object-contain  rounded-xl" src="https://ziplinelogistics.com/wp-content/uploads/2019/02/best-by-food-beverage-e1612397879396.jpg">
        
            <div class="flex-col mt-2 md:mt-8 justify-center" >
            <h1 class="text-4xl p-4 text-center">Welcome to <span style="font-family: 'Rampart One', cursive;"> Expiration Generator!</span></h1>
                <p class="px-8 mx-8 text-lg">The way expiration dates are currently printed on food packaging make it incredibly dificult to locate
            and tend to easily smudge. An easy solution to this problem is printing a qr-code that when scanned will tell you the expiration date. No more guesswork on whether the number printed is a 5 or a 3, 
            or other problems that come with the traditional way of printing expiration dates.  </p>
            </div>   
        </div>
            <h2 class="text-center mt-4 text-2xl">How it Works</h2>
            <div class="flex grid-cols-2 m-8">
          <div class="mx-8 basis-1/2">
            <p>1. Create a new user. Make sure to sign up with your company's name because it will show on every page your qr code links to</p>
            <p class="mt-4 ">2. Once you're logged, in add your company's logo</p>
            </div>
            <div class="mx-2 md:mx-8 basis-1/2">
            <p>3. Start creating your QR Codes! All you need to add is your product name and expiration date and we'll do the rest</p>
            <p class="mt-4">4. Once you've created your first QR code you'll see it on your profile page with the options to view the generated page, edit the information inputed and download the image</p>
            </div>
            </div>
    <p class="font-medium text-center">Each QR code will link to a page that displays your company name, logo, and of course the expiration date you entered. </p>    
        </div>
    </div>
</div>